services:
  web:
    build: .
    command: sh -c "python manage.py migrate && gunicorn -b 0.0.0.0:8000 infrastructure.project.wsgi:application"
    volumes:
      - ./src/:/app
    ports:
      - "8000:8000"
    env_file:
      - path: .env
        required: true
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=faucet
      - POSTGRES_USER=faucet_user
      - POSTGRES_PASSWORD=faucet_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  transactions_checker:
    build: .
    command: sh -c "python manage.py check_transactions_status"
    restart: always
    env_file:
      - path: .env
        required: true
    depends_on:
      - db