# Generated by Django 5.1.4 on 2024-12-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaucetTransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('success', 'SUCCESS'), ('failed', 'FAILED'), ('pending', 'PENDING')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('wallet', models.CharField(db_index=True, max_length=42)),
                ('amount', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faucet_transactions',
            },
        ),
    ]
